name: pixiv_func_mobile
description: Pixiv 第三方客户端

publish_to: 'none'
version: 1.0.0-beta34+39

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  json_annotation: ^4.5.0
  get: ^4.6.5
  dio: ^4.0.6
  crypto: ^3.0.2
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3
  extended_image: ^6.2.1
  extended_nested_scroll_view: ^5.1.3
  extended_sliver:
    git: https://github.com/git-xiaocao/extended_sliver.git
  waterfall_flow: ^3.0.2
  pull_to_refresh_notification: ^2.3.0
  loading_more_list: ^5.0.2
  html: ^0.15.0
  permission_handler: ^10.0.0
  image_picker: ^0.8.5+3
  encrypt: ^5.0.1
  device_info_plus: ^4.1.2
  connectivity_plus: ^2.3.5
  expandable: ^5.0.1
  visibility_detector: ^0.3.3
  path: ^1.8.2
  uni_links2: ^0.6.0+2
  share_plus: ^4.0.10+1
  path_provider: ^2.0.11
  app_installer: ^1.1.0
  flutter_local_notifications: ^9.9.0
  pixiv_live_proxy_server: ^0.0.2
  extended_text: ^9.1.1
  extended_text_field: ^10.1.1
  video_player: ^2.4.7
  #  唤醒锁
  wakelock: ^0.6.2
  #  设备方向
  orientation: ^1.3.0
  image: ^3.2.0
  cool_dropdown: ^1.4.2
  pixiv_dart_api:
    git: https://github.com/git-xiaocao/pixiv_dart_api.git
  #  path: ../pixiv_dart_api

dev_dependencies:
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/stamps/
    - assets/emojis/
  fonts:
    - family: iconFont
      fonts:
        - asset: assets/icon.ttf